services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./gcp-key.json:/tmp/gcloud-key.json:ro
      - /home/moazelbeshbeshy/.ssh/google_compute_engine:/home/jenkins/.ssh/gcp-key.pem:ro
    restart: unless-stopped

volumes:
  jenkins_home:
