pipeline {
    agent any

    environment {
        GCP_PROJECT_ID = 'm06308803865'
        BACKEND_IMAGE = "gcr.io/${GCP_PROJECT_ID}/task-manager-backend"
        FRONTEND_IMAGE = "gcr.io/${GCP_PROJECT_ID}/task-manager-frontend"
        TAG = 'latest'
        GCP_VM_SSH = 'moazelbeshbeshy@34.116.160.135'
        SSH_KEY_PATH = '/home/jenkins/.ssh/gcp-key.pem' 
    }

    stages {
        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }

        stage('Build Frontend Assets') {
            steps {
                dir('task3/frontend') {
                    sh 'npm ci'
                    sh 'npm run build'
                }
            }
        }

        stage('Build Frontend Docker Image') {
            steps {
                dir('task3/frontend') {
                    sh """
                    docker build -t ${FRONTEND_IMAGE}:${TAG} .
                    """
                }
            }
        }

        stage('Build Backend Docker Image') {
            steps {
                dir('task3/backend') {
                    sh """
                    docker build -t ${BACKEND_IMAGE}:${TAG} .
                    """
                }
            }
        }

        stage('Authenticate with GCP') {
            steps {
                withCredentials([file(credentialsId: 'gcp-key', variable: 'GOOGLE_APPLICATION_CREDENTIALS')]) {
                    sh '''
                        gcloud auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS    
                        gcloud config set project ${GCP_PROJECT_ID}
                        gcloud auth configure-docker --quiet
                    '''
                }
            }
        }

        stage('Push Docker Images to GCR') {
            steps {
                sh """
                docker push ${FRONTEND_IMAGE}:${TAG}
                docker push ${BACKEND_IMAGE}:${TAG}
                """
            }
        }

        stage('Deploy on GCP VM') {
            steps {
                withCredentials([file(credentialsId: 'gcp-ssh-key', variable: 'SSH_KEY')]) {
                    sh """
                        chmod 600 $SSH_KEY
                        ssh-keygen -lf $SSH_KEY
                        ssh -i $SSH_KEY -o StrictHostKeyChecking=no moazelbeshbeshy@34.116.160.135 << 'EOF'
                        echo ✅ Connected to GCP VM
                        docker pull gcr.io/m06308803865/task-manager-frontend:latest
                        docker stop frontend || true
                        docker rm frontend || true
                        docker run -d --name frontend -p 80:80 gcr.io/m06308803865/task-manager-frontend:latest
                        EOF
                    """
                }
            }
        }
    }

    post {
        success {
            echo '✅ Deployment succeeded!'
        }
        failure {
            echo '❌ Deployment failed.'
        }
    }
}
